#ifndef QTINTERACTIVEOSMC_GLOBAL_H
#define QTINTERACTIVEOSMC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTINTERACTIVEOSMC_LIBRARY)
#  define QTINTERACTIVEOSMCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTINTERACTIVEOSMCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTINTERACTIVEOSMC_GLOBAL_H
